site_name: Hakowan - A 3D Data Visualization Grammar

repo_url: https://github.com/qnzhou/hakowan

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    - search.suggest
    - search.highlight
    - content.code.copy
  logo: images/hakowan_logo.svg
  favicon: images/hakowan_logo.svg

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: orange
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: grey
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode


plugins:
- mkdocstrings:
    handlers:
      python:
        options:
          docstring_style: google
          show_root_heading: false
          show_root_toc_entry: false
          preload_modules:
          - hakowan
- search


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      url_download: true
  - pymdownx.superfences
  - toc:
      permalink: true
  - attr_list
  - footnotes
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg


nav:
- Home: index.md
- User guide:
  - Grammar: guide/grammar.md
  - Data: guide/data.md
  - Mark: guide/mark.md
  - Channel: guide/channel.md
  - Transform: guide/transform.md
  - Attribute: guide/attribute.md
  - Scale: guide/scale.md
  - Material: guide/material.md
  - Texture: guide/texture.md
  - Layer: guide/layer.md
  - Configuration: guide/config.md
- Gallery: gallery.md
- Reference:
  - Data: api/data.md
  - Mark: api/mark.md
  - Channel: api/channel.md
  - Transform: api/transform.md
  - Attribute: api/attribute.md
  - Scale: api/scale.md
  - Material: api/material.md
  - Texture: api/texture.md
  - Layer: api/layer.md
  - Color: api/color.md
  - ColorMap: api/colormap.md
  - Medium: api/medium.md
  - CurveStyle: api/curve_style.md
  - Configuration: api/config.md
