""" Default parameters
"""

DEFAULT_POSITION = "@geometry"
DEFAULT_UV = "@uv"
DEFAULT_NORMAL = "@normal"

DEFAULT_COLOR = "ivory"
DEFAULT_CURVE_COLOR = "darkslategray"
DEFAULT_POINT_COLOR = "gold"
DEFAULT_ROUGHNESS = 0.5
DEFAULT_METALLIC = 0.0

DEFAULT_SIZE = 0.02
