name: Build and test

on: push

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Test
        run: pipx run tox

      - name: Build wheels
        run: pipx run build

      - name: Check metadata
        run: pipx run twine check dist/*

