name: Build and deploy

on:
  push:
    tags:
      - '*'

jobs:
  build_wheel:
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Test
        run: pipx run tox

      - name: Build wheels
        run: pipx run build

      - uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: ./wheelhouse/*.whl

      - name: Check metadata
        run: pipx run twine check dist/*

  upload_pypi:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    needs: [build_wheel]
    environment:
      name: pypi
      url: https://pypi.org/p/hakowan
    permissions:
      id-token: write

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: artifact
          path: dist

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
